name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks and congrats for opening your very first issue in this project.You may submit a PR on the same if you like!Hope you have a great time here :)'
        pr-message: 'Thankyou and congarts for your first PR on this project.We will review it soon!'
